apiVersion: v1
kind: Service
metadata:
  name: avalon-back-nodeport
spec:
  type: NodePort
  selector:
    app: avaloncliente
  ports:
    - name: avaloncliente
      protocol: TCP
      port: 80
      targetPort: 80