CREATE TABLE [dbo].[UsuarioPermissaoPagina](

	[UsuarioId] [int] NOT NULL,

	[PaginaId] [int] NOT NULL
	
 CONSTRAINT [PK_UsuarioPermissaoPagina] PRIMARY KEY CLUSTERED 
(
	[UsuarioId],[PaginaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

