name: Kubernetes Deployment

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID_NAME }}
  CLUSTER_NAME: nome-do-seu-cluster
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
        # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"
      
      # Authenticate with Google Cloud using the provided KUBE_CONFIG_DATA
      - name: Authenticate with GKE
        run: echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Set kubectl context
        run: kubectl config use-context gke_${PROJECT_ID}_${REGION}_${CLUSTER_NAME}

      - name: Build and tag the Docker image
        run: |
          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA -f docker/dockerfile
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f K8s/deployment.yaml